### ISSUE TITLE
Best app. But need more features.

### ISSUE THREAD

**Issue by Suaib100** [tyron12233/CodeAssist#110]
Like
-layout editor
-debugger
-logcat viewer
-sketchware to code assist
-code assist to sketchware pro
-last compile error not seved problem solve
-editor theme
-project publisher
-download free projects and import it
--
Etc features.
I wish it should be the best android Aide.

**Comment by GreenCityLife** [comment]
What!?!? Sketchware to CodeAssist and CodeAssist to Sketchware pro? Are you kidding?

**Comment by thewolfprod** [comment]
@GreenCityLife
I moved a fairly large project from Sketchware to CodeAssist and after (not a lot) corrections it works . But from CodeAssist to Sketchware I think it won't work.

**Comment by Suaib100** [comment]
I think it's somehow possible

**Comment by Suaib100** [comment]
@Suaib100 Yes

**Comment by tyron12233** [comment]
Most of the features you have mentioned are already on the project road map. (Take a look at the readme for the roadmap). 

## Sketchware Pro Projects
There are no plans to support exporting CodeAssist projects to Sketchware Pro as these two are very different IDEs and does not use the same build tools.

## Last diagnostics
- If you swipe up from the bottom of the screen (from the symbols view) you can see the logs of the previous build and the errors in the current file that you're editing.
- 
![Screenshot_20220201-163337_CodeAssist](https://user-images.githubusercontent.com/74818961/151936139-47ba333a-e853-414f-9373-beb051d7e59f.png)
![Screenshot_20220201-163325_CodeAssist](https://user-images.githubusercontent.com/74818961/151936163-1aeb5a7f-7c7e-45af-99fa-cbf6cd104a3a.png)
