### ISSUE TITLE
Image loading library no support and crash the app

### ISSUE THREAD

**Issue by Kawsar167** [tyron12233/CodeAssist#117]
The image loading no support codeassist like picasso and others image loading library

**Comment by tyron12233** [comment]
Have you added glide or picasso as a dependency?

**Comment by Kawsar167** [comment]
Yes i am try but not working run my app and open then crash my app

**Comment by tyron12233** [comment]
Can you send the built APK here?

**Comment by Kawsar167** [comment]
Yah wait a few minutes

**Comment by Kawsar167** [comment]
I'm just added dependency

**Comment by tyron12233** [comment]
Any updates on the compiled APK so I can check it?

**Comment by Revakumar** [comment]
Hey @Kawsar167, how did you added dependencies, can you reply how to add in library manager

**Comment by Kawsar167** [comment]
You see, Picasso is not working
