### ISSUE TITLE
Error Layout Editor

### ISSUE THREAD

**Issue by rdm600** [tyron12233/CodeAssist#118]
![Screenshot_20211230-145400_CodeAssist.jpg](https://user-images.githubusercontent.com/53654451/147749864-04c23ffb-1334-463e-8153-d7d69bc1c648.jpg)

**Comment by tyron12233** [comment]
Are you using a selector as a source in an ImageView?

**Comment by rdm600** [comment]
> Are you using a selector as a source in an ImageView?

To be honest, this happens everywhere, even where there is no ImageView
