### ISSUE TITLE
setContentView Error 

### ISSUE THREAD

**Issue by MiawApp** [tyron12233/CodeAssist#120]
![Screenshot_2021-12-31-22-58-13-711_com tyron code](https://user-images.githubusercontent.com/74065184/147831517-5075ea1b-7363-4e5f-b8ec-10dfb6233ee1.jpg)

There is an error

**Comment by PranavPurwar** [comment]
add
import com.gabut.R;

**Comment by MiawApp** [comment]
it's the same no change still error

Pada tanggal Jum, 31 Des 2021 23.03, Pranav ***@***.***>
menulis:

**Comment by tyron12233** [comment]
Build the app for the first time or open any xml file
