### ISSUE TITLE
Adding local repositories

### ISSUE THREAD

**Issue by dhaigit** [tyron12233/CodeAssist#121]
Can I use my offline local repository? I tried the following but didn't work.

maven {
    url '/my-local-repository'
}

What about using anything else other than google() and mavenCentral()?

**Comment by Iyxan23** [comment]
please note that CodeAssist does not use gradle, it only parses implementation statements and adds them as dependencies, any other gradle-related tasks can not be done in CodeAssist: https://github.com/tyron12233/CodeAssist#note

**Comment by dhaigit** [comment]
I did see that your app doesn't use gradle. What I was trying to ask was how do I tell your app where to look for the dependencies? Is there a setting in your app where I can specify a location, or multiple locations?

**Comment by Iyxan23** [comment]
oh, there's no way to do that currently as far as I'm aware

**Comment by Rajmani7584** [comment]
you can add local maven dependencies and it's pom.xml to app's data folder (it is /sdcard/Android/data/com.tyron.code/files/cache)  then edit /app/app_config.json with dependencies of your library dependency then it should be work

**Comment by tyron12233** [comment]
There has been support of adding external maven URLs internally however I havent added a UI for it yet. What repository url are you trying to add so I can test it?

**Comment by dhaigit** [comment]
I'm not looking at anything in particular. I think having just google() and mavenCentral() as the only places to look for dependencies is too limited. The other option that we need to copy dependencies to the app's "files" folder and add one by one to the library manager is only manageable for small projects with a few dependencies.

I have a local maven repository in the phone's storage. The way I usually do is add this...
Maven {
    url 'path-to-my-local-maven-repository'
}
...to the project's build.gradle, in the "repositories" tags that are under the buildscript and allprojects sections.

It would be nice if your app could support doing things that way. The app should be able to take a provided maven repository path and use it as an additional place to look for dependencies. Also, it should treat it as a maven repository and not just simply as a flatDir.

**Comment by tyron12233** [comment]
I would change the structure of how the app caches the libraries to follow the maven repository structure, is this correct?

```
repository-name
  L group-id
    L artifact-id
      L version-name
        L name.jar
        L name-sources.jar
        L (other files)
```

**Comment by dhaigit** [comment]
By "version-name", you meant, for example, "1.3.0" and not "1.3.0-core", right?

Yeah, that structure looks okay. The IDE would also automatically and recursively try to find dependencies of dependencies from the user-provided maven repository URL(s), correct?

**Comment by tyron12233** [comment]
Yes i meant the version only. Yes, if the link given follows the above format then the IDE would be able to recursively find its dependencies through its POM file. (The dependency resolver just appends the above format to the repository URL and checks if it doesn't throw an exception)

**Comment by dhaigit** [comment]
Great. Please give it a shout when it's implemented so I could try it out.

**Comment by tyron12233** [comment]
I have changed the library structure to follow the given format. It is saved in the app's external directory (`Android/data/com.tyron.code/files/caches`).

You can specify custom repositories in the `repositories.json` inside the app module directory. Here's an example
```json
[
  {
    "name": "google-maven",
    "url": "https://maven.google.com"
  }
]
```

This will add the google maven repository to a list of URLs that the dependency manager will search. To add local repository, set the url to null and just copy the its content to `Android/data/com.tyron.code/files/cache/{repo-name}`. Heres an example

root folder: `Android/data/com.tyron.code/files/cache/mylocal-repo`
```json
[
  {
    "name": "mylocal-repo",
    "url": null
  }
]
```

**Comment by tyron12233** [comment]
![image](https://user-images.githubusercontent.com/74818961/151935132-b01f5a13-910c-4de3-8310-4ce349adca47.png)
heres the sample structure generated from [this unit test](https://github.com/tyron12233/CodeAssist/blob/a47886f361245affd31580702c69ff2b69928b0e/dependency-resolver/src/test/java/com/tyron/resolver/RepositoryManagerTest.java)

**Comment by dhaigit** [comment]
I hope this is only temporary as I see that there's still an issue with the local repository.

A repository is usually huge with thousands and thousands of small files. It takes a long time to copy or delete. So it should (preferably) stay put at a fixed location. However, the app's home storage space is meant to be removed when it's uninstalled.

I would not recommend doing it this way as, in addition to the long copying time, it would also degrade the device storage quickly.

A workaround by running an external server on the device might work but I'm not sure.

I don't remember exactly but the old AIDE allowed us to do this, didn't it? Is there a reason you need to do this in the app's private space? Is it because of permission issues?

**Comment by tyron12233** [comment]
this would be the preferred way for android 10 and higher. i have already tried using the all file access permission but it has been rejected in play store. also adding the all file access permission would mean that users will be able to open projects from the external storage where file read and write performance is significantly worse

**Comment by dhaigit** [comment]
I'm not going to try to copy my local repository to the app's private storage space as having a repository copy just for this app that's going to get removed after uninstalling is not practical.

However, by using a local server along with the app, it's using my local repository to build with no problems. So that's great.

I have only tested on an Android 8 so I wouldn't know how this setup would do on an Android 10+ yet.

**Comment by tyron12233** [comment]
But yes, on android 10 and below I will add the ability to add local repositories with a custom path on the url.

**Comment by dhaigit** [comment]
Using ACTION_OPEN_DOCUMENT_TREE, can't the IDE ask the user to keep the local repository somewhere other than root, Download, Android/data, and Android/data directories? Would that work for Android 11+ without the all files access (which is only allowed on PlayStore if the app is of specific types)?

**Comment by dhaigit** [comment]
I have found some problems.

1. If the "repositories.json" is malformed or has errors, even with just a comma, the IDE would crash. We wouldn't be able to open the project anymore because of the crashing popup. The only way is to edit the json file to hopefully correct everything with an external text editor.

2. Auto identation in json editing is misbehaving. (just move the cursor to the end of a line and press enter a few times to see)

3. When "libraries.json" file is open, selecting "Add libraries from build.gradle" has no effect.

**Comment by dhaigit** [comment]
The three problems have been retested and seem to have been fixed.

**Comment by dhaigit** [comment]
I know you still need to figure out the best way to implement this with the file access issues for local files, but would you, for now, add a setting option for remote repositories so I could just stick my locally run server's URL there and wouldn't have to keep editing the repositories.json for new projects?
