### ISSUE TITLE
It doesn't change app version

### ISSUE THREAD

**Issue by Thatsmynameinthechat** [tyron12233/CodeAssist#128]
After update/ change app codes , version it doesn't change in the app ,so please resolve that issue and add ease of copy paste button, add the symbols upper side of keypad.
Auto check option of language means suggestions. 
Please reply on my gmail if issue resolve or not .
Contact on my gmail : taksomekonta@gmail.com

**Comment by tyron12233** [comment]
CodeAssist does not use gradle, if you are editing the version from the `build.gradle` file, it won't work. Edit the `app_config.json` file instead located on the same folder where the build.gradle file is located.

Copy paste options can be shown by tapping the selected text after selecting it.
