### ISSUE TITLE
Unable to open project.

### ISSUE THREAD

**Issue by gdb417** [tyron12233/CodeAssist#13]
When you enter the application, you cannot open a previously created project.

**Comment by alluhemanth27** [comment]
Are you sure that you are using the latest version of CodeAssist ?
![Screenshot_20211108-163230_CodeAssist.png](https://user-images.githubusercontent.com/93532546/140730912-0ef9a234-c74e-443a-8887-708ec88286cc.png)

It now has list of projects

**Comment by gdb417** [comment]
I build  the app yesterday.

**Comment by alluhemanth27** [comment]
Try downloading it from [here](https://github.com/tyron12233/CodeAssist/actions/runs/1429016448)

**Comment by gdb417** [comment]
Installed the application from your link.  Same.  The created project is not displayed in the list.  Android 9, Miui 11.

**Comment by alluhemanth27** [comment]
It currently gets list of Projects from Android/data/com.tyron.code/Projects

**Comment by gdb417** [comment]
I looked.  The Project folder is empty.

**Comment by alluhemanth27** [comment]
That's because you saved the Project in some other location

**Comment by gdb417** [comment]
Reset application settings to default.  The project files appeared in the Project folder.  But the project still doesn't show up in the app.

**Comment by gdb417** [comment]
Video_

https://user-images.githubusercontent.com/13872830/140735215-a7b9c4bd-b83a-45e1-a50f-e63d15e95001.MP4

**Comment by alluhemanth27** [comment]
Thanks for that it currently checks Projects in Android/data/com.tyron.code/Projects only if the Android version is >= 11, It should also get projects from the data folder for all android versions. 
![Screenshot_20211108-171854_Chrome.png](https://user-images.githubusercontent.com/93532546/140737018-a4e37ee7-e9d3-4c45-bf21-eccf52e1faab.png)

**Comment by gdb417** [comment]
Here is the content of the preferences file after building the project and exiting the application.
![Screenshot_2021-11-08-14-54-51-141_bin mt plus](https://user-images.githubusercontent.com/13872830/140737870-ddabefd9-b401-436b-bc54-dcbb07db0fd2.jpg)

**Comment by tyron12233** [comment]
> Video_
> 
>  Screenrecorder.MP4

here on the video you sent, you canceled the dialog on where to display the current projects can you try selecting a directory?

**Comment by gdb417** [comment]
I've tried selecting a directory.  It gets written to preferences (see screenshot above), but the project is not displayed.

**Comment by tyron12233** [comment]
Okay, the issue was it saves the project directly into /Projects, instead of /Projects/ProjectName. Thanks! ill try to fix it in the next version.

**Comment by gdb417** [comment]
Thank you!

**Comment by gdb417** [comment]
Hi. You haven't completely fixed the problem.  Incorrect path specified when creating a project.  And one more problem is that you cannot change the directory for saving projects.  All this I tried to show you in the video.  I first select the Test folder and then the Test1 folder.

https://user-images.githubusercontent.com/13872830/141373130-c74d1fa8-af62-497f-867c-4bc9fcccdf93.mp4
