### ISSUE TITLE
Import New Libraries 

### ISSUE THREAD

**Issue by Revakumar** [tyron12233/CodeAssist#130]
Dear CodeAssist Team, How do I can add new libraries for code assist project in library manager. Please reply to this issue so we can add libraries.and give us an example with screen shot. We don't know to put artifact id, group id, version, soo please reply to this issue

**Comment by alluhemanth27** [comment]
Hello there,
Here's an example on how to use library manager
If you wanna use a dependency like `implementation 'com.google.android.material:material:1.4.0'`
```
Group Id: com.google.android.material
Artifacat Id: material
Version: 1.4.0
```
It's just simple just split the dependency by `:`

**Comment by alluhemanth27** [comment]
A tutorial or an example might be added soon, Thank You

**Comment by Revakumar** [comment]
Bro how to implement androidx dependencies

**Comment by thewolfprod** [comment]
"It's simple, just split the dependency by :"
I don't understand why we need do it, and it's not done right away programmatically...

**Comment by tyron12233** [comment]
Theres now an option to add dependencies from build.gradle from the library manager. Ill add an option in the future to add libraries directly by pasting the `groupId:artifactId:version` string
