### ISSUE TITLE
Building Error

### ISSUE THREAD

**Issue by MrJohnSilva** [tyron12233/CodeAssist#131]
I'm trying to integrate an ads network sdk called Appodeal
I have downloaded the jar file from a github demo then I included it to my project
When dexing the library, this error shown:

ERROR: com.android.tools.r8.internal.r8: Cannot create android app from an archive '/storage/emulated/0/CodeAssist/Appodeal Test/app/build/libs/975d752e80f283adeb479f6d0dd57231/classes.jar' containing both DEX and Java-bytecode content

I think this error is related to MultiDex
This is common error & I hope that CodeAssest will be able to build this project

This is the Appodeal Demo open source github
[https://github.com/appodeal/appodeal-android-demo](https://github.com/appodeal/appodeal-android-demo)

**Comment by tyron12233** [comment]
The error is pretty self explanatory, it says `The jar contains both bytecode and DEX`. Just remove the dex file inside the jar that you provided

**Comment by NaincyKumariKnoldus** [comment]
Hello @MrJohnSilva I want to solve this issue. Can I?

**Comment by MrJohnSilva** [comment]
> Hello @MrJohnSilva I want to solve this issue. Can I?

Yes, sure
I would be thankful for you
The problem is that this Appodeal jar file works with Android Studio but with CodeAssest found this error
I can provide you with all information about Appodeal sdk integration

**Comment by MrJohnSilva** [comment]
@tyron12233 I don't think so
Because, it this sdk works with Android Studio programmers
But I use only CodeAssest, cause I don't have pc

Can we build this project with CodeAssest?
https://github.com/appodeal/appodeal-android-demo
If you can build it with Android Studio & CodeAssest to make sure.

Thanks in advance.

**Comment by tyron12233** [comment]
Can you send the jar file you used?

**Comment by MrJohnSilva** [comment]
@tyron12233 This is what I used. It's old one & it works with Android Studio

https://github.com/ResoCoder/AppodealAndroidIntegrationTutorial/blob/master/app/libs/appodeal-2.1.7.jar

**Comment by tyron12233** [comment]
i have converted the library into `aar` format, can you check if it works? https://file.io/XsB9kBMoz0U2

**Comment by MrJohnSilva** [comment]
@tyron12233 > i have converted the library into aar format, can you check if it works? https://file.io/XsB9kBMoz0U2

Well done 😻
Thank you very much, now it works
I want to know wat was the problem.

Another request please
Would you please download the latest version of the library & convert it to aar format for me?
This is the latest version:
implementation 'com.appodeal.ads:sdk:2.11.0.+'
And this is the Appodeal Github Demo
https://github.com/appodeal/appodeal-android-demo

Also this library cannot be downloaded by CodeAssest which is required for Appodeal Ads
implementation 'com.explorestack:consent:1.0.5'


Thank you again.

**Comment by tyron12233** [comment]
For converting a library into aar format just follow this structure:

```
Root folder
  L assets
  L res
  L AndroidManifest.xml
  L classes.jar
```
