### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by user74273** [tyron12233/CodeAssist#136]
ERROR: /storage/emulated/0/Android/
data/com.tyron.code/files/Projects/
AERO Downloader/app/src/main/
AndroidManifest.xml:22:18-91 Error:
Attribute application@appComponentFactory
value=(android.support.v4.app.CoreComponen
tFactory) from
AndroidManifest.xml:22:18-91
is also present at
AndroidManifest.xml:22:18-86
value= (androidx.core.app.CoreComponentFact
ory).
Suggestion: add
'tools:replace="android:appComponentFactor
y"! to <application> element at
AndroidManifest.xml:10:5-26:19 to
override.

When I add dependency to my project this error occur

**Comment by tyron12233** [comment]
Is this already solved? (from the telegram group)

**Comment by tyron12233** [comment]
Ill be closing this issue assuming this is already solved, feel free to reopen this issue again if thats not the case
