### ISSUE TITLE
Status bar colo

### ISSUE THREAD

**Issue by Revakumar** [tyron12233/CodeAssist#137]
Dear CodeAssist team, can you tell me how to change status bar olor of CodeAssist app. I'm changing colorPrimaryVariant color also it not working please can you reply me

**Comment by ZERODEVcuba** [comment]
I have the same problem 🥲

**Comment by thewolfprod** [comment]
@Revakumar 
@ZERODEVcuba 
You should have something like this in Themes.xml

`
 
        <item name="android:statusBarColor" tools:targetApi="l">#FFFFFF</item>
		<item name="android:windowLightStatusBar">true</item>
`

**Comment by tyron12233** [comment]
For questions like this, please ask on the discord server or the telegram group.

Invite link: https://discord.gg/pffnyE6prs
Telegram group: @codeassist_app
