### ISSUE TITLE
Error in the compiled package

### ISSUE THREAD

**Issue by Mirivan** [tyron12233/CodeAssist#142]
I get an error about a broken package after building if I add a json format file to the resources. Helps apk signing with zipsigner.
![IMG_20220117_223306_325](https://user-images.githubusercontent.com/54078891/149815351-dd51b77f-8a86-4c88-ab3d-aca299e93c0b.jpg)

**Comment by tyron12233** [comment]
CodeAssist doesn't currently support zip aligning, you can try to use zipalign for now using termux

**Comment by deenu713** [comment]
> CodeAssist doesn't currently support zip aligning, you can try to use zipalign for now using termux

Can we use zip align as binary

**Comment by tyron12233** [comment]
Zip align has been added on 0.2.5
