### ISSUE TITLE
Anydpi icons not supported

### ISSUE THREAD

**Issue by Mirivan** [tyron12233/CodeAssist#143]
![Screenshot_20220118-130737_CodeAssist](https://user-images.githubusercontent.com/54078891/149896194-406f50ad-dc21-42df-934a-b2ef40818aba.png)

**Comment by tyron12233** [comment]
The current AAPT2 task seems to treat all texts that it has outputted as an error, ill fix on the next version. Thanks!

**Comment by tyron12233** [comment]
This has been fixed with the invocation of AAPT2 through JNI.
