### ISSUE TITLE
Automatically add libraries for imported projects

### ISSUE THREAD

**Issue by franciscowilton** [tyron12233/CodeAssist#144]
Recently, the way to add libraries to the application has changed, now it is necessary to add them to the "Library manager".

For new projects, it's fine, but for imported projects that contain a lot of libraries, it becomes boring and time-consuming to keep adding one by one in him.

It would certainly be extremely useful to add the libraries automatically when importing a project.

**Comment by tyron12233** [comment]
Only projects created `before` the library manager was introduced will need to add libraries to the library manager, any existing CodeAssist project will have it saved already in the `libraries.json` file at the app module. To help migrate from using build.gradle to the library manager, theres now an option to get libraries from the gradle file in the library manager menu.

**Comment by franciscowilton** [comment]
> Only projects created `before` the library manager was introduced will need to add libraries to the library manager, any existing CodeAssist project will have it saved already in the `libraries.json` file at the app module. To help migrate from using build.gradle to the library manager, theres now an option to get libraries from the gradle file in the library manager menu.

Will this menu be available in the next version?

**Comment by tyron12233** [comment]
Yes, its already implemented in the latest commits and will be available next version.
