### ISSUE TITLE
Relative Layout

### ISSUE THREAD

**Issue by mjf-inisial** [tyron12233/CodeAssist#145]
Relative Layout won't show on 'Preview Layout'...

**Comment by tyron12233** [comment]
please include as much details as possible, can you share the layout file and some screenshots?

**Comment by mjf-inisial** [comment]
![Screenshot_2022-01-19-20-43-00-82](https://user-images.githubusercontent.com/67011095/150142598-f9812af1-32c1-4239-a762-a834be2587f2.png)
![Screenshot_2022-01-19-20-43-40-90](https://user-images.githubusercontent.com/67011095/150142627-28fa4343-c777-4e59-8063-e176c880a41e.png)
![Uploading Screenshot_2022-01-19-20-43-51-92.png…]()

The first image is 'Preview Layout' with LinearLayout. The second and third are using RelativeLayout. It won't show the Layout and set the name of attributes as 'Unknown'.

**Comment by mjf-inisial** [comment]
![Screenshot_2022-01-19-20-43-00-82](https://user-images.githubusercontent.com/67011095/150143992-d0098c80-0023-437d-8b1e-6dc5dea0980b.png)
![Screenshot_2022-01-19-20-43-40-90](https://user-images.githubusercontent.com/67011095/150143998-0db35486-5dc5-4821-a3a9-1dde913cd3ff.png)
![Screenshot_2022-01-19-20-43-51-92](https://user-images.githubusercontent.com/67011095/150144008-6baab967-1aee-45bf-8c12-fa6272cbeeee.png)

The first image is 'Preview Layout' with LinearLayout. The second and third are using RelativeLayout. It won't show the Layout and set the name of attributes as 'Unknown'.

**Comment by mjf-inisial** [comment]
![Screenshot_2022-01-19-20-43-00-82](https://user-images.githubusercontent.com/67011095/150144303-2c3a4034-0124-4b01-8905-4f5069cdb47e.png)
![Screenshot_2022-01-19-20-43-40-90](https://user-images.githubusercontent.com/67011095/150144315-d79ba17a-c732-4fb5-a684-132b0536364c.png)
![Screenshot_2022-01-19-20-43-51-92](https://user-images.githubusercontent.com/67011095/150144321-6fd42e50-b318-49d5-be16-07166156d572.png)
![Screenshot_2022-01-19-20-53-20-98](https://user-images.githubusercontent.com/67011095/150144365-5473c871-5ad9-4020-92dc-a14d25e456ee.png)

The first image is 'Preview Layout' with LinearLayout. The second and third are using RelativeLayout. It won't show the Layout and set the name of attributes as 'Unknown'. The last is my layout file.

**Comment by tyron12233** [comment]
Please reopen this issue if you are still facing this issue on the next version.
