### ISSUE TITLE
Version Code and Version Name

### ISSUE THREAD

**Issue by ZERODEVcuba** [tyron12233/CodeAssist#156]
How can I change the version name and version code of my project, I have changed it in the manifest and in the build.gradle and it has no effect. Thanks

**Comment by tyron12233** [comment]
CodeAssist does not use gradle so editing the build gradle file won't have any effect. It has its own configuration file for that, it's located in 

```
Project
  L app
    L app_config.json
```
You will see other values that you can change there. After editing the file, don't forget to press `Refresh project`

**Comment by ZERODEVcuba** [comment]
Thank you
