### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by DevTryon** [tyron12233/CodeAssist#159]
Tyron bhai library manager se kaam nhi chalega agar maan lo kisi ko koi file implement karni ho build gradel me to oo usko implement kaise karega dependence maan lo thik hai. id dali version dala uske baad add ho gyi but koi other project hai agar usko bhi ise project me implementation karna hai to kaise kroge kya id uski daloge aur konsa version uska daloge. isliye bola ki build gradel ki dependence bhi work kare aur Library manager ki bhi kare. aur Library manager me jo upar back button add kiye ho oo work nhi kar raha hai usko bhi fix karo baki app sahi chal raha hai wahi ek issu ta ki koi dusre project ki file main project me kaise implementation kare kyuki build gradel ki dependence work nhi karti na. alag se library manager se add karna padta hai dependence ko but file ko dependence ke andar implementation kaise kare library manager se yahi janna tha

thank u

**Comment by tyron12233** [comment]
Please use english for writing issues as I do not understand them. I have tried using google translate for this but it was not able to translate it too.

**Comment by tyron12233** [comment]
Reopen the issue with the details written in English. Thanks

**Comment by PranavPurwar** [comment]
lemme translate it for you: he's asking for gradle because he wants to add different modules as dependency on his main project

**Comment by PranavPurwar** [comment]
or in short: some kind of module system
