### ISSUE TITLE
ID ERROR

### ISSUE THREAD

**Issue by BinMasoodOfficial** [tyron12233/CodeAssist#187]
See the screenshot 
![Screenshot_20220210-102007_CodeAssist](https://user-images.githubusercontent.com/99382561/153342702-89091917-32a9-4a85-8405-6c39ad321cb4.jpg)
![Screenshot_20220210-102022_CodeAssist](https://user-images.githubusercontent.com/99382561/153342728-8f023da8-f9a4-4fac-a608-f4a7f36917a3.jpg)
![Screenshot_20220210-102033_CodeAssist](https://user-images.githubusercontent.com/99382561/153342761-f82b980b-aa9c-4361-8ed7-8d1ba490e9ca.jpg)

**Comment by tyron12233** [comment]
The proper declaration of an id is
```xml
android:id="@+id/button"
```

All the other stuff was working an intended (The diagnostics where showing properly)

**Comment by AidosZhaqyp** [comment]
In your xml file when you're creating a new id you need to write "@+id/someid"
