### ISSUE TITLE
Kotlin Project App Crash

### ISSUE THREAD

**Issue by Deenu713** [tyron12233/CodeAssist#19]
Kotlin Project build output Crashing when it successfully installation , the apk doesn't open

**Comment by tyron12233** [comment]
Can you send the apk or the project?

**Comment by Deenu713** [comment]
I decompiled the apk the MainActivity.kt is not compiling at the running time, others are working perfectly, so the app is crashing

**Comment by tyron12233** [comment]
Are you using the latest version from github actions?

**Comment by Deenu713** [comment]
2 days before

**Comment by gdb417** [comment]
I just compiled and ran the Kotlin application from the examples that are in the application itself without any problems.

**Comment by Deenu713** [comment]
Working now,
