### ISSUE TITLE
Operation not permitted 

### ISSUE THREAD

**Issue by fgsoftware1** [tyron12233/CodeAssist#192]
**To Reproduce**
1. Click on plus button
2. Select any template
3. Fill the all fields 
4. Click on create 

**Expected behavior**
Appear an snackbar with this error

**Screenshots**
![Screenshot_20220210-205622.jpg](https://user-images.githubusercontent.com/60277618/153495033-d1fbff16-eec6-464d-855a-757f670ce1c0.jpg)

**Smartphone (please complete the following information):**
 - Device: Huawei p8 lite 2017
 - OS: Android 8.0
 - Version: latest play store version

**Comment by tyron12233** [comment]
It seems like you are trying to save to your sdcard. CodeAssist does not support saving through sdcard as android does not allow access to it through `java.io` APIs

**Comment by fgsoftware1** [comment]
fd0ee0f5b07e113d4a9ee81998548692194be0c3

Fix problem
