### ISSUE TITLE
Projects view error

### ISSUE THREAD

**Issue by nrid3v** [tyron12233/CodeAssist#193]
After update if i open the app i see this.

 - Device: OnePlus 7T Pro
 - OS: RROS 8.7.3
 - Version: 0.2.6 ALPHA

![Screenshot_20220211-051654387](https://user-images.githubusercontent.com/25800553/153536964-d3cea848-19da-4ff7-bbde-d31e7c075c26.jpg)

**Comment by tyron12233** [comment]
Fixed in this commit https://github.com/tyron12233/CodeAssist/commit/6c66b12e34aca85204c7b7b84747b0bd052104ac
