### ISSUE TITLE
Files becoming blank 

### ISSUE THREAD

**Issue by bdmohammed** [tyron12233/CodeAssist#197]
**Note that Issues are for bugs only. Use the discussions tab for feature requests.**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tyron12233** [comment]
Please edit the bug report template and fill up the issue template properly. It would help me identify whether this issue has already been fixed or is a duplicate.

What version of the app are you on?
Where did you download the app? (e.g google play, github releases, github actions)
What file are you editing? (e.g xml, java, kotlin)
