### ISSUE TITLE
aab Process Task

### ISSUE THREAD

**Issue by Deenu713** [tyron12233/CodeAssist#20]
I Have added successfully Aab Module Task but When I it run the Base.zip to convert it to aab it says TMP/zipbuilder.tmp not found any solution
![Screenshot_20211116-184247](https://user-images.githubusercontent.com/82932744/141992252-22349238-aa4b-452c-adba-f0a76ccf6a16.png)

But in termux it successfully converted the base.zip to aab
![Screenshot_20211116-184114](https://user-images.githubusercontent.com/82932744/141992335-1e0ff902-b9d1-489f-ba0f-112873be61d3.png)

![Screenshot_20211116-184228](https://user-images.githubusercontent.com/82932744/141992299-4b1de44e-06c7-483c-a449-b195efe6a3f1.png)

**Comment by tyron12233** [comment]
Can you share relevant code about getting the zip file?

**Comment by Deenu713** [comment]
> Can you share relevant code about getting the zip file?

Okay

**Comment by Iyxan23** [comment]
can't wait for the PR, good luck :)

**Comment by Deenu713** [comment]
In GDrive

**Comment by Deenu713** [comment]
![Screenshot_20211116-200307](https://user-images.githubusercontent.com/82932744/142004753-29c71828-7b9b-4d08-a668-570cce877ae5.png)
In termux it successfully converted to aab

**Comment by Iyxan23** [comment]
> In GDrive HERE IT IS https://drive.google.com/file/d/1-OtAaO21QL7_rBwLjBXC9zhhOwvRHyA3/view?usp=drivesdk Or [Source Code.zip](https://github.com/tyron12233/CodeAssist/files/7547099/Source.Code.zip)

you should create a some kind of fork and modify your things there, it would be easier for us to inspect the changes ;)

**Comment by Deenu713** [comment]
> > In GDrive HERE IT IS https://drive.google.com/file/d/1-OtAaO21QL7_rBwLjBXC9zhhOwvRHyA3/view?usp=drivesdk Or [Source Code.zip](https://github.com/tyron12233/CodeAssist/files/7547099/Source.Code.zip)
> 
> you should create a some kind of fork and modify your things there, it would be easier for us to inspect the changes ;)

Ohh I am new in GitHub so I haven't knowledge  but I will try

**Comment by tyron12233** [comment]
The problem seems to be that you're invoking the bundle tool through dalvikvm, and BundleTool creates a temp file but instead of the cache dir, dalvikvm returns /tmp/

**Comment by Iyxan23** [comment]
> > > In GDrive HERE IT IS https://drive.google.com/file/d/1-OtAaO21QL7_rBwLjBXC9zhhOwvRHyA3/view?usp=drivesdk Or [Source Code.zip](https://github.com/tyron12233/CodeAssist/files/7547099/Source.Code.zip)
> > 
> > 
> > you should create a some kind of fork and modify your things there, it would be easier for us to inspect the changes ;)
> 
> Ohh I am new in GitHub so I haven't knowledge but I will try

oh okay, just press the fork button and create your changes on the fork :)

once your changes is ready, you could do a "pull request" to this repository, where you propose changes to this repository to be merged :+1:

**Comment by Deenu713** [comment]
> The problem seems to be that you're invoking the bundle tool through dalvikvm, and BundleTool creates a temp file but instead of the cache dir, dalvikvm returns /tmp/

Where  can I get That c.getFileDir() "cache/tmp/" so can edit and test I searched but not found in codes

**Comment by tyron12233** [comment]
you can try adding the bundletool.jar as a library, and then call BundleToolMain#main(String[]) directly

**Comment by Deenu713** [comment]
> you can try adding the bundletool.jar as a library, and then call BundleToolMain#main(String[]) directly

Okay

**Comment by tyron12233** [comment]
you can also try passing the arguments `"-Djava.io.tmpdir=/" + context.getCacheDir().getAbsolutePath()`

**Comment by Deenu713** [comment]
Thankyou very much its working now I done it with dalvikvm -Xcompiler-option --compiler-filter=speed -Xmx256m -Djava.io.tmpdir=/data/user/0/jackpal.androidterm/cache and this is working on Terminal emulator now Before it was not working, I am not able to port BundleTool.jar latest I am getting errors, so I will do with it dalvikvm
