### ISSUE TITLE
Files not saved to disk

### ISSUE THREAD

**Issue by IsaacOfc** [tyron12233/CodeAssist#206]
I had problems with a code, I wrote a code that had an error that was reported by Build Logs, then I deleted all the invalid code and tried to compile again, but unfortunately the Build Logs presented the same error as when the code was there! 

as if the code previous previous was still there, every time I delete some code it's like it's still in the editor

I solved it as follows, I closed the tab that was open "MainActivity.java" and reopened it through the application's own file manager and I managed to compile the code without errors, I believe it's just a bug in the editor's "autosave" and that it's simple to solve, I hope they solve it ^ ^

 - Device: Galaxy j7neo
 - OS: Android
 - Version: 9Pie

I'm using the latest version of the app: 0.2.6.1 ALPHA

**Comment by tyron12233** [comment]
Thanks for the detailed report, the issue has already been fixed in [this commit](https://github.com/tyron12233/CodeAssist/commit/3cdbfb70faa3a9e291e24580e5c536423f1c5c14) and will be available on the next version.
