### ISSUE TITLE
Does not save the changes

### ISSUE THREAD

**Issue by ZERODEVcuba** [tyron12233/CodeAssist#208]
When making changes to my code CodeAssist doesn't save the changes though press refresh module. I tried to exit the application and enter again and to my surprise the code is not there. my device is a Poco x3 Pro Android 11 App version: 0.2.6.1 ALPHA sorry for my english, i'm using the translator.

**Comment by tyron12233** [comment]
Thanks for reporting, the issue has already been reported here #206 and will be available next version. Refer to the mentioned issue for updates about this.

**Comment by hosnifraj0** [comment]
@ZERODEVcuba that's happens to me too
