### ISSUE TITLE
AutoCompletion issues

### ISSUE THREAD

**Issue by dhaigit** [tyron12233/CodeAssist#213]
1. Autocompletion results are missing "auxilary" (defined outside of main class but in the same file as main class, and required to have package-private qualifier, i.e., no class qualifier) classes.

2. Prioritization of completion results, a lot of the time, isn't too good. Sometimes dissimilar results are on top while a more matching result is somewhere below.

The point of using autocompletion is so that we don't have to type stuff out exactly, and with less typing as possible. Currently, we need to type out, sometimes almost, the whole word (even with letter case matching required) in order to find the one we need.

In my opinion, it's better with the following:

-user would type in without having to think about letter casing (to eliminate that prefixed SHIFT key that feels so unnecessary for a natural and fluent user experience) 

-completion results would then be listed with this prioritization:
a. partial but exact matches, including letter case
b. partial but exact matches, NOT including letter case
c. keywords
d. local variables
e. global variables
f. other classes

**Comment by tyron12233** [comment]
For class names, its still required to have the first letter capitalized to keep the completions fast. Including the class names on fuzzy search will pollute the completion list with class names.

**Comment by dhaigit** [comment]
>For class names, its still required to have the first letter capitalized to keep the completions fast.
>
The gain is very insignificant that users probably wouldn't be able to notice.

I have tried to compare this letter casing toggle in other IDE's and felt no improvement in speed having it on, and my search became more comfortable and faster without touching the SHIFT key when casing is off. You could try to compare them for yourself and see.

I would trade this (insignificant gain) for getting rid of the maddening practice of having to prefix my search with SHIFT. 

If it won't be changed, would it at least be an optional toggle in settings for those who really dislike using that SHIFT key?

>Including the class names on fuzzy search will pollute the completion list with class names.
>
The fuzzy search list is already poluted to begin with, but if the prioritization is working correctly, wouldn't it matter since the ones we want should be on top and that "polution" at the bottom? If fuzzy search requires users to type the extra key each time, I would prefer using the normal search instead. I thought "fuzzy search" would mean it's more general and requiring less specifics.

**Comment by dhaigit** [comment]
Fixed, and fixed.
Much better matching now, and (woohoo!) no more Mr. SHIFT key for me!
