### ISSUE TITLE
Not saving changes 

### ISSUE THREAD

**Issue by John-kener** [tyron12233/CodeAssist#215]
I am using this application on my samsung galaxy a2 core device which runs android 8.1.0 version...

I created just a demo application with code assist and it worked well ,But when i went 2nd time to the editor to update my previous project i noticed that code assist is not saving my changes to the files (It is not saving my codes realtime).When i export application there is no change in my demo app which i have done seconds ago...
And after few moments i just closed the project & opened again & i there was only half of codes which i wrote before.

This is a big issue for the application ,and i suggest you to add save button for better user experience ....

And i suggest you to add a confirmation dialog before a user close the project ,As i noticed that when i just pressed back button it closes the whole project...

If anyone have any problem or more suggestions of this issue ,please comment below.

**Comment by tyron12233** [comment]
Thanks for your report, the issue has already been reported in #206. The fix will be available on the next version. To avoid duplicates like this please check the existing issues first as I have renamed them for easier recognition.

**Comment by John-kener** [comment]
Ok that's my fault ,However Thank you for solving this problem...
