### ISSUE TITLE
App version in manifest not working

### ISSUE THREAD

**Issue by NehaDevs** [tyron12233/CodeAssist#216]
Codeassist version :- 0.2.6.1(latest version)

Android manifest not working

When I change the version of my app from 1.0 to 1.1 and version code from 1 to 2 i built the release apk but the app version not changed it was still 1.0 i reloaded codeassit files and built app still doesn't worked pls fix it soon I want to release a update of my app

Smartphone :- Lenovo M10 tab

**Comment by dhaigit** [comment]
I think #156 is the answer you're looking for.

**Comment by NehaDevs** [comment]
> I think #156 is the answer you're looking for.

Thanks it helped
