### ISSUE TITLE
Build using R8

### ISSUE THREAD

**Issue by gdb417** [tyron12233/CodeAssist#22]
If R8 is enabled, compilation stops with an error when building in debug mode.  In release mode, compilation works fine.  Also, please kindly correct the file name for creating rules from proguard-rules.txt to proguard-rules.pro as is customary everywhere.  And ideally, make the parser from build.prop work

**Comment by gdb417** [comment]
![Screenshot_2021-11-18-17-13-08-338_com.tyron.code.jpg](https://user-images.githubusercontent.com/13872830/142431544-2e802b64-bbd4-4902-937a-782cf5c1f93c.jpg)

**Comment by tyron12233** [comment]
Seems like R8 still runs on debug mode, I only intended it to run in a release build. I will fix it tomorrow when I have access to my computer. Thanks!

**Comment by TimScriptov** [comment]
@tyron12233 you have Google Play Console? To distribute your compiler
