### ISSUE TITLE
The Button overlap in library dependencies on CodeAssist V0.2.7 ALPHA

### ISSUE THREAD

**Issue by ArjunaKumarMohanta** [tyron12233/CodeAssist#223]
![IMG_20220216_054750.jpg](https://user-images.githubusercontent.com/87923185/154172911-59a676ef-4629-4d4f-a10b-ccc9c92f23d9.jpg)

**Comment by tyron12233** [comment]
already solved in https://github.com/tyron12233/CodeAssist/commit/27192c857ef388441bcde55c9a6a107d2513c2a4
