### ISSUE TITLE
Overlapping codeAssist sidebar to mobile statusbar 

### ISSUE THREAD

**Issue by getsettalk** [tyron12233/CodeAssist#224]
Hello sir, codeAssist app having a new issue in sidebar where showing project all files and folders , that is overlapping to my phone status bar you can see in this screenshot 

**Screenshots**
![Screenshot_2022-02-16-08-44-16-97_2870cb4d7e72f8050b62d08052357b72](https://user-images.githubusercontent.com/49394996/154189879-4a2af423-593d-462b-a06c-fb17e9553bad.jpg)

In this photo you can view on status bar where showing time and other app icon ,that gone overflow.

Please fix this. 

🥰🥰💝💝💝

**Smartphone (please complete the following information):**
 - Device: Realme
 - OS: Android 10
 - Version 10

**Additional context**

**Comment by tyron12233** [comment]
Thank you for reporting, there is already a bug report for this. To keep the issues clean please take a look first if someone has already reported the issue using Github's search function. For updates about this issue, refer to #222
