### ISSUE TITLE
All files get closed after a module refresh

### ISSUE THREAD

**Issue by dhaigit** [tyron12233/CodeAssist#225]
Was this behavior intended?

It happens after a cold start, after you quickly open some files. When the initial module refesh is done, all open files get closed.

This can also be reproduced by, first, open some files. Then select "refresh module" from menu. When done refreshing, all files get closed.

It seems like there's something unstable going on while a module refresh is in progress. I don't know if it was related or not but once, the autocompletion went crazy and some classes (String classes) were missing from suggestions. It could have happened because I was trying to do autocompletion and module refresh was still in progress.

I have also traced the issue 5 from #186 to this.

These are the things that could go wrong while (and/or after) a module refresh is in progress:
-all files get closed (most of the time)
-in the few times when they don't close, keys on symbol input bar no longer register (but bar is still scrollable)
-autocompletion service sometimes gets wonky or even stops working altogether
-doing things and navigating around the app becomes laggy
-filetree resets (users need to make a bunch of clicks again to get to the file they want to open)

**Comment by tyron12233** [comment]
Currently the app only saves the list of opened tabs before the project is closed so when refreshing the module it tries to restore back to the state where it was initially opened. Ill try to save this state before re-indexing.

Issue 5 from #186 should be fixed on this commit https://github.com/tyron12233/CodeAssist/commit/8eaadc2b131e8e96889001c535becf63ff466401. As apparantly Fragment#isDetached still returns false even if the context is already null.

During indexing, auto complete and error highlighting are limited or not available. This is because resource files and classes such as R.java are generated during indexing.

**Comment by dhaigit** [comment]
A manual module refresh now preserves the opened files state, but the initial (opening project from a cold start and opening files before it's done indexing) refresh still closes files and doesn't open them back after.

**Comment by dhaigit** [comment]
Shouldn't the indexing operation have saved the state right before trying to close all the files?

**Comment by tyron12233** [comment]
During indexing, the project is considered to be "not yet opened" and files the user that have opened will be recognized as it doesn't belong to the project. When the index have finished, the `editor_opened_files` is read in the projects settings key and will then override the opened files. What do you think should be the behavior? One way i'm thinking right now is to open the saved editors right before indexing

**Comment by dhaigit** [comment]
Isn't the problem about "when" it (the state) should be saved though? If it doesn't do this "right before" it closes files then it would not have the files opened after the indexing starts.

I just know the current behavior is not too user-friendly where file tabs would just suddenly disappear. Users would be annoyed or thought something happened to their files.

**Comment by dhaigit** [comment]
Ahh I see.
How would it handle the following scenario:
-editor_opened_files has fileA and fileB
-user opens fileC
-user taps refresh

Would fileC now disappear and be replaced by fileA and fileB?

**Comment by dhaigit** [comment]
I've tested with the latest CI buildd. As I have mentioned before, I think it really matters "when" we save that state of opened files. The issue is still there. It's just mutated a little. Files now just disappear and reappear after each refresh.

To reproduce:
-Open a project and let it finish indexing
-Open MainActivity.java and AndroidManifest.xml
-Select "Refresh module" from menu
-When done refreshing, files disappear
-Select "Refresh module" again
-When done refreshing, files reappear
-Repeating...

**Comment by dhaigit** [comment]
I have tested v0.2.8 ALPHA (16) and the problem is exactly the same as before.
@tyron12233
Did you try the steps from my previous post and it worked for you? I'm sure there are other cases in which file tabs are appearing and reappearing after indexing also and that was just one example.

**Comment by dhaigit** [comment]
In v0.2.8.2 ALPHA, when cold starting (after app has been swiped off), if there are some file tabs saved, the Project button doesn't respond even after indexing is done. We need to close and open the file again, or, if there are more than one tab, switch tabs in order for the button to work.

**Comment by dhaigit** [comment]
Anyone running on Android 8.0, would you please confirm this issue?
