### ISSUE TITLE
Manifest Merge Problem

### ISSUE THREAD

**Issue by Deenu713** [tyron12233/CodeAssist#23]
When I tried to use another project or implementing new libs it gives error use tools overide use library,  I solved one by one but there is in so many how to solve

**Comment by tyron12233** [comment]
You have to explicitly add `<uses-sdk android:targetSdkVersion="sdkVersion"/>` on the manifest

**Comment by gdb417** [comment]
> You have to explicitly add `<uses-sdk android:targetSdkVersion="sdkVersion"/>` on the manifest for now

Even after adding this line to the manifest, an error occurs during assembly (Version code not found)

**Comment by Deenu713** [comment]
> > You have to explicitly add `<uses-sdk android:targetSdkVersion="sdkVersion"/>` on the manifest for now
> 
> Even after adding this line to the manifest, an error occurs during assembly (Version code not found)

It is solved, 

> > You have to explicitly add the manifest for now
> 
> Even after adding this line to the manifest, an error occurs during assembly (Version code not found)

It is solved thanks, we already updated in templates. I wasn't that was problem for merge,  If outside project opens need to use this method. If it says also making while aab its need version code and target SDK version for aab

**Comment by Deenu713** [comment]
Brother do you have any group or channel so I can join or subscribe.

**Comment by gdb417** [comment]
After building AAB, the program tries to install the package, but the installer reports an error.  I think because the package is not signed.

**Comment by tyron12233** [comment]
Its no longer needed to add `<uses-sdk android:targetSdkVersion="sdkVersion"/>`, it will be injected automatically based on the values present in `app_config.json`
