### ISSUE TITLE
App not responsive

### ISSUE THREAD

**Issue by TechnicalStudioDevelopers** [tyron12233/CodeAssist#230]
**Note that Issues are for bugs only. Use the discussions tab for feature requests.**

**Describe the bug**

Hello developer i am facing a issue in code assist that is reposiveness your app is not responsive in my devise see screen shot

**To Reproduce**
1. Go to 'App.'
2. Click on 'Any project'
3. Click on drawer

**Expected behavior**

**Screenshots**

![Screenshot_2022-02-17-14-13-37-048_com tyron code](https://user-images.githubusercontent.com/96680248/154438288-2bc91cde-86a8-402a-b105-d039a853c75f.jpg)

**Smartphone (please complete the following information):**
 - Device: [Redmi 9]
 - OS: [10]
 - Version [0.2.7 Alpha(15)]

**Comment by tyron12233** [comment]
Thank you for reporting, there is already a bug report for this. To keep the issues clean please take a look first if someone has already reported the issue using Github's search function. For updates about this issue, refer to #222
