### ISSUE TITLE
Drop-down of doesn't show 

### ISSUE THREAD

**Issue by getsettalk** [tyron12233/CodeAssist#231]
Hello 🤗, codeAssist app having a new issue for drop-down open not showing like add : center, start etc.

You can see : in video

https://user-images.githubusercontent.com/49394996/154449420-ba447f6a-b197-4c26-8a7d-140d138c1dfc.mp4

Please fix taht

**Smartphone (please complete the following information):**
 - Device: Realme
 - OS: Android
 - Version : 10

**Additional context**

**Comment by tyron12233** [comment]
As listed in 0.2.7's change log, this feature is *temporarily* removed while I work on improving the feature.
