### ISSUE TITLE
Error in R.id

### ISSUE THREAD

**Issue by IsaacOfc** [tyron12233/CodeAssist#235]
There is an error that insists that the "id" or "layout" doesn't exist, but it does! 

R.id.something 
R.layout.something 

They turn red in the diagnosis. 

I have to restart the app every time to recognize it.

 - Device: Galaxy J7Neo
 - OS: Android
 - Version 9

I am using the latest version of the application 0.2.7 ALPHA

**Comment by NehaDevs** [comment]
It's just a fake error and will do nothing restart your app to solve it or check your package file on top it's correct or not.

**Comment by officialblog30** [comment]
> 

Hello sir I'm using Android TECNO Spark 8c, and I downloaded the App from Playstore but yet immediately after I start importing or let me say the App program processing and ready to build either APK or AAB file but it is telling me that Package R does not exist; meanwhile I've not yet editing, please say something. I have uninstalled and installed but no solution comes
