### ISSUE TITLE
Building CodeAssist

### ISSUE THREAD

**Issue by dhaigit** [tyron12233/CodeAssist#238]
Sometimes when there's an important fix but not a release yet, and I would like to test it out, I try to build CodeAssist with all current commits.

I don't do it too often as there are little things here and there that I need to modify before I could successfully build it. One of them is the boring step of changing the "buildToolsVersion" in "android {}" in build.gradle of many of CodeAssist project's modules and sub-modules. Since buildToolsVersion isn't specified in CodeAssist's modules, it always defaults to a version according the currently used AGP.

It would be very helpful if you could keep buildToolsVersion (and possibly some other common specifications, maybe compileSDK?) centralized in your project so that we would only need to change them at one place.

I know this isn't a user's issue, but maybe it could help in some way. Please move to discussion if need be.

**Comment by tyron12233** [comment]
I would do that but if you want another way to build CodeAssist, you can just fork the repo and run `Android CI`, the build process would usually take about 5 minutes.
