### ISSUE TITLE
After building AAB, the program tries to install the package, but the installer reports an error.  I think because the package is not signed.

### ISSUE THREAD

**Issue by Deenu713** [tyron12233/CodeAssist#24]
After building AAB, the program tries to install the package, but the installer reports an error.  I think because the package is not signed.

The classes.dex file have been changed so the base/dex all dex is not for aab so it is generating issue, we need to make settings for enable aab if you to use, 

_Originally posted by @gdb417 in https://github.com/tyron12233/CodeAssist/issues/23#issuecomment-974040823_

**Comment by tyron12233** [comment]
Are you on the latest commit? I have already added a menu for compiling aab.

**Comment by Deenu713** [comment]
> Are you on the latest commit? I have already added a menu for compiling aab.

I saw just, sorry for that. It  is awesome let me try

**Comment by gdb417** [comment]
> Are you on the latest commit? I have already added a menu for compiling aab.

There is a menu.  The point is that after building aab, the program tries to install the assembled APK.  This should be disabled.
