### ISSUE TITLE
Projects Path cleared when selecting cancel

### ISSUE THREAD

**Issue by dhaigit** [tyron12233/CodeAssist#242]
When selecting Projects Path from the 3-dotted menu on Projects page, then hitting cancel or device's back key, the current Projects Path gets cleared. We should be able to change our mind and go back without an unwanted change.

**Comment by dhaigit** [comment]
I'm using the lastest CI build and the path clearing problem is still there. Now it seems there are also some additional little issues.

1. Projects Path get cleared when prompt dialog is dismissed.
2. Dialog keeps showing twice. (sometimes once)
3. Projects page does a little flash of something before showing the projects (to reproduce: On Projects page, tap "+" button then tap back key.

BTW, was [3ac5caf](https://github.com/tyron12233/CodeAssist/commit/3ac5caf06bfb22b164384ebebd1da4753dd4c217) meant for #225?

**Comment by tyron12233** [comment]
Yes, its still not labeled as "Fixed but not closed", please wait for it to be labeled as fixed before trying it out to save time.

**Comment by PriNova** [comment]
To fix 1. & 2.
In the ProjectManagerFragment.class where the two MaterialDialogBuilders are used set property to
`.setCancelable(false)`
befor 
`.show()`

**Comment by dhaigit** [comment]
In v0.2.8 ALPHA, current Projects Path still gets cleared for me after canceling or backing out from the Projects Path selection dialog.

**Comment by tyron12233** [comment]
The last directory you were on should be saved and restored, like the following: 


https://user-images.githubusercontent.com/74818961/155823511-6b29d311-b4ec-4d45-9fde-91d4d25a4717.mp4

**Comment by dhaigit** [comment]
That's weird. I have tried again dozens of times to make sure but it's exactly the same result. I'm running it on Android 8.0 by the way.

Did the path get cleared for you on previous version?

**Comment by NoOneCho** [comment]
> Anyone running on Android 8.0, would you please confirm this issue?

I have same issue

https://user-images.githubusercontent.com/100952177/156790653-b0dfec75-f502-4318-9b51-5f7f47998072.mp4
