### ISSUE TITLE
Problem indicators (squiggly lines) are a little hard to see

### ISSUE THREAD

**Issue by dhaigit** [tyron12233/CodeAssist#244]
Problems (typos, warnings, errors) should "pop out" when we're looking at our code. Currently, the squiggly lines are too thin and are a bit hard to see, even if we give the colors enough contrast.

Could we customize the thickness of the squiggly lines?

**Comment by tyron12233** [comment]
I think you should report this to the [editor library's repo](https://github.com/Rosemoe/sora-editor/issues) as I have no control to the width of the error spans.
