### ISSUE TITLE
Faster copy/paste actions

### ISSUE THREAD

**Issue by dhaigit** [tyron12233/CodeAssist#246]
Currently, we can't quickly copy/cut text. We need to go through:

1. Double-click, tap and hold selection, click  "Text actions"
or,
2. Hold to make selection, click "Text actions"

That's quite a lot of things to do or time to wait, for something we would do very often.

Could we just single-click on a selection and see the cut/paste/... actions directly?

**Comment by tyron12233** [comment]
In the future, users will be able to put custom menus through the `Actions API`, and to prevent the initial popup to consume the whole screen, I placed it in an `ActionGroup`.

A better way to improve this is through the `drag to open` behavior of android menus. The behavior is you long press on the editor and then you keep long pressing and release your finger on the action you want to perform.

https://user-images.githubusercontent.com/74818961/155026171-449202c1-fa9b-4d58-a343-f36be0620d3f.mp4

**Comment by dhaigit** [comment]
I haven't built it with the latest commits so I haven't tried it yet. Maybe you could make a CI build?

Looking at the clip, it seems better than the old hold-then-tap, but what I had in mind was this.

The old behavior was that, if we hold to select, it shows the actions menu, and if we double-click to select, it does "not" show the actions menu (and we are free to use the handles right away to adjust the selection.) That was nice intuitive and I actually liked it up to that part.

What I would suggest is if we had a text selection, the following single-click on it would show the cut/copy/paste actions directly. If a selection was made by holding, then we do what you had in your demo clip.

We had two ways of making a selection so why not use one for each case. What do you think?

**Comment by tyron12233** [comment]
The old behavior is still there, you can still double tap to select the text without the action menu popping up. The thing that was changed is that you need to long press the selected text again now to select from the popuo menu. (Before it was a tap only) this was changed to better match android's native text selection behavior

**Comment by dhaigit** [comment]
The "native text selection behavior" you mentioned refers to when text was not selected yet. This is after the text has been selected. If you do this again, it's the same thing as having to hold two times. If one hold took 1 seconds, each selection would take 2 seconds. When doing this a thousand times, we're wasting more than half an hour without realizing it. In a day, it could even be a lot more than that.

I understand the "initial cluttering issue" you have mentioned earlier, but that could be taken care of by the (one time) hold-select-slide (from an unselected state), as you've demonstrated in the clip.

The double-click selection could be dedicated for only expand/copy/cut/paste and not anything else. Requiring to hold and tapping another sub-menu here don't really give any benefits but only slow down the process and waste our coding time.
