### ISSUE TITLE
Dexing error

### ISSUE THREAD

**Issue by ani1nonly** [tyron12233/CodeAssist#251]
If same class is present in different libs, it fails to compile, I can provide screen shot if required

**Comment by tyron12233** [comment]
This is an intended behavior and happens on android studio too. An APK cannot have the same class inside it. You need to resolve them yourself, CodeAssist provides a way to exclude transitive dependencies. Please take a look at the `Excluding dependencies` section in https://github.com/tyron12233/CodeAssist/releases/tag/ALPHA-0.2.3

**Comment by ani1nonly** [comment]
Project compiles without any error on gradle(android studio/aide with gradle).

**Comment by tyron12233** [comment]
The issue is with the library `com.faendir:acra:4.10.0`, CodeAssist does not currently support using `android support` libraries together with `androidx` libraries.
