### ISSUE TITLE
Gradle

### ISSUE THREAD

**Issue by Deenu713** [tyron12233/CodeAssist#26]
![Screenshot_20211121-233018](https://user-images.githubusercontent.com/82932744/142773582-c77983d1-de98-4d62-89d6-5d0500ddf940.png)
![Screenshot_20211121-232949](https://user-images.githubusercontent.com/82932744/142773591-13e85376-c219-4df3-85bc-56acf00d7342.png)

How can I add multiple commands at same time like :- cd storage/emulated/0/Project
gradle build

So it can be work with gradle too.

**Comment by tyron12233** [comment]
I suggest appending the openjdk binaries to the PATH environment variable this way you would be able to call `java` from anywhere. Then you could just set the working directory to the project directory first. However if you are planning to add this to CodeAssist, I don't recommend it as executing native binaries are no longer supported in android 10+

**Comment by remakerofficial** [comment]
Can you send me this aide version link?

**Comment by Deenu713** [comment]
> Can you send me this aide version link?

In telegram it's my own version 
https://t.me/Deenu713

**Comment by Deenu713** [comment]
> I suggest appending the openjdk binaries to the PATH environment variable this way you would be able to call `java` from anywhere. Then you could just set the working directory to the project directory first. However if you are planning to add this to CodeAssist, I don't recommend it as executing native binaries are no longer supported in android 10+

How do I set that working directory.

**Comment by Deenu713** [comment]
> I suggest appending the openjdk binaries to the PATH environment variable this way you would be able to call `java` from anywhere. Then you could just set the working directory to the project directory first. However if you are planning to add this to CodeAssist, I don't recommend it as executing native binaries are no longer supported in android 10+

Thanks i solved it
