### ISSUE TITLE
Query 

### ISSUE THREAD

**Issue by MidlajYH** [tyron12233/CodeAssist#262]
Is there any plans to add more programming languages to the app? Like Javascript in future versions?

**Comment by BanDroid** [comment]
So, you dont clearly know the difference between IDE and Code Editor?

**Comment by LohitaMohanta** [comment]
****

**Comment by tyron12233** [comment]
The app is focused for android development and will only support languages that are used for it. (Except C/C++).

Advanced support for other languages such as error highlighting and code completion are unlikely to be added.

**Comment by MidlajYH** [comment]
Alright my friend, thanks for the reply 👍🏻
