### ISSUE TITLE
Error while building CodeAssist project

### ISSUE THREAD

**Issue by gdb417** [tyron12233/CodeAssist#27]
When I try to build a project in release mode, I get an error.

`Type org.jetbrains.kotlin.com.intellij.openapi.util.JDOMUtil$1 is defined multiple times: D:\CodeAssist\kotlinc\build\.transforms\669ea267485f63b49509bb85c89cc809\transformed\release\dex\classes.dex, D:\CodeAssist\app\build\intermediates\external_libs_dex\release\mergeExtDexRelease\classes5.dex`

**Comment by tyron12233** [comment]
fixed with https://github.com/tyron12233/CodeAssist/commit/45be250e26027e30c6471bab568bdaf1efc3c383
