### ISSUE TITLE
Not showing Project Path Option

### ISSUE THREAD

**Issue by LohitaMohanta** [tyron12233/CodeAssist#271]
![Screenshot_2022-03-01-06-07-32-339_com tyron code](https://user-images.githubusercontent.com/100362821/156082541-4ba68304-8f61-4cbb-8d13-165445ba52f5.jpg)

![Screenshot_2022-03-01-06-03-14-037_com tyron code](https://user-images.githubusercontent.com/100362821/156082212-a0c6a4ff-70ab-40d9-8d0e-a6841f7cc6b8.jpg)
Not showing Project path option

**Comment by tyron12233** [comment]
You cannot change the project path in android 11+ due to storage restrictions.
