### ISSUE TITLE
Not showing CodeAssist App icon on Notification Bar

### ISSUE THREAD

**Issue by LohitaMohanta** [tyron12233/CodeAssist#274]
**CodeAssist V0.2.8.2 ALPHA**

When I open my project and then I show my notification bar CodeAssist App icon not showing.

Device: Xiaomi Redmi 8
OS: MIUI 12 12.5.2 Stable
Version: 0.2.8.2 ALPHA

![IMG_20220303_204017.jpg](https://user-images.githubusercontent.com/100362821/156593195-1e922049-dc22-4200-b623-b7bcf453dffe.jpg)

**Watch on YouTube**
https://youtu.be/Z07y4_SohNw

**Comment by tyron12233** [comment]
fixed on https://github.com/tyron12233/CodeAssist/commit/80c2447bc2486375cb9ebb8fedaef3816e2fdc15
