### ISSUE TITLE
Auto completion is not reliable

### ISSUE THREAD

**Issue by dhaigit** [tyron12233/CodeAssist#277]
In v0.2.8.2 ALPHA, auto completion sometimes malfunctions in which only keywords are recognized. I've not found a reliable list of step to reproduce the issue.

[Edit]
This seems to be similar to #276

**Comment by tyron12233** [comment]
Duplicate of #276, bug introduced in https://github.com/tyron12233/CodeAssist/commit/7096a49d397313eebe9db62f1635aae67fe5dd55
