### ISSUE TITLE
Attempting to enter a code on MIUI will bring up the Xiaomi Security Keyboard

### ISSUE THREAD

**Issue by CodePwn2021** [tyron12233/CodeAssist#278]
**Describe the bug**
Attempting to enter a code on MIUI will bring up the Xiaomi Security Keyboard

**To Reproduce**
1. Trying enter something

**Expected behavior**
Pop up the input method I'm using instead of the Xiaomi Secure Keyboard

**Screenshots**
![Screenshot](https://s4.ax1x.com/2022/03/02/b1x5h4.jpg)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 10 Pro
 - OS: MIUI 13 Development Version (22.2.28,Android12)
 - Version 0.2.8.2 ALPHA
 code on MIUI will bring up the Mi Security Keyboard

**Comment by vip458** [comment]
So is mine

**Comment by CodeCrazy-ywt** [comment]
Go to Settings — Editor, and switch on “enable keyboard suggestions”.
![IMG_20220308_205519](https://user-images.githubusercontent.com/62426149/157242788-e6095cf0-ab72-4dbc-b9f0-5583fb04c648.jpg)
