### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by gdb417** [tyron12233/CodeAssist#28]
During the build of the Empty project, if you add lines to the dependencies, then an error occurs.

`implementation "android.arch.persistence.room:runtime:1.0.0"
    annotationProcessor "android.arch.persistence.room:compiler:1.0.0"`

![Screenshot_2021-11-23-12-45-42-994_com tyron code](https://user-images.githubusercontent.com/13872830/143002195-251b8182-7ebe-4f0e-8e88-43a23110052b.jpg)

File from /build/bin :
![Screenshot_2021-11-23-12-48-47-769_bin mt plus](https://user-images.githubusercontent.com/13872830/143002607-9e5acfed-06b7-4e6d-b774-df83a6669d2f.jpg)

**Comment by tyron12233** [comment]
You have to add the tools namespace on the manifest with `xmlns:tools="https://schemas android.com/tools"`

note that annotation processors are not currently supported as it may violate google play policies in the future (loading unsigned code/dex files at runtime from unknown sources)

**Comment by gdb417** [comment]
Thanks.  That helped.
