### ISSUE TITLE
Squiggling where there's not supposed to be

### ISSUE THREAD

**Issue by CodeCrazy-ywt** [tyron12233/CodeAssist#284]
**Note that Issues are for bugs only. Use the discussions tab for feature requests.**

**Describe the bug**
Showing errors where there's no errors.

**To Reproduce**
1. Create a kotlin project with API 29
2. Paste following code to `MainActivity.kt`:
```kotlin

package com.ywt.pushups

import androidx.appcompat.app.AppCompatActivity
import android.view.View
import android.widget.TextView
import android.os.Bundle

public class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
         super.onCreate(savedInstanceState)
         setContentView(R.layout.activity_main)
    }
	
	fun increase(view: View) {
		if (view !is TextView) throw Exception()
		view.text = (view.text.toString().toInt() + 1).toString()
	}
}
```
3. Wait a few seconds to see what appears

**Expected behavior**
There's no red squiggles.

**Screenshots**
![Screenshot_2022-03-02-22-34-31-402_com tyron code](https://user-images.githubusercontent.com/62426149/156383779-94501521-25e8-4088-b943-ee49e9fce77c.jpg)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 11
 - OS: MIUI 13 22.3.2 Beta
 - Version 0.2.7 ALPHA

**Additional context**
1. The diagnoatic information for `override` is “'onCreate' overrides nothing”; others “Unresolved reference”.

2. `activity_main.xml`:
```xml

<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textSize="72dp"
        android:text="0"
	android:onClick="increase"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

</androidx.constraintlayout.widget.ConstraintLayout>
```

3. This code can be normally compiled and works well.

**Comment by rdm600** [comment]
Please upgrade to version 0.2.8.2.

**Comment by thewolfprod** [comment]
_Please upgrade to version 0.2.8.2._

I do not know how in Kotlin, but in Java (on the latest version of CodeAssist) this error also occurs, and when it occurs, the code hints do not work either.
