### ISSUE TITLE
Project delete 

### ISSUE THREAD

**Issue by pisu5** [tyron12233/CodeAssist#315]
When i cancel path and back to main, there is show no project......Fix this bugs as soon as possible i lost my whole project

**Comment by tyron12233** [comment]
Related to #242. However your projects are not deleted, CodeAssist just sees a different directory your files are still there.

**Comment by Trasd** [comment]
@pisu5 Make sure you minimize the keyboard and tap the "Create" button.  Otherwise, you're canceling out of the project creation screen.
