### ISSUE TITLE
GitHub Actions assemble build failed

### ISSUE THREAD

**Issue by Deenu713** [tyron12233/CodeAssist#32]
![Screenshot_20211130-124435](https://user-images.githubusercontent.com/82932744/144002438-b3d6da16-83c6-4539-9a90-b5d62a2edbcf.png)
Jvm Heap Size how to solve

**Comment by tyron12233** [comment]
Have you tried increasing the memory size in `gradle.properties`

**Comment by tyron12233** [comment]
Does this issue still occur after updating the memory size in gradle.properties?

**Comment by Deenu713** [comment]
> Does this issue still occur after updating the memory size in gradle.properties?

It is solved.

**Comment by tyron12233** [comment]
Alright thanks
