### ISSUE TITLE
Bug tag

### ISSUE THREAD

**Issue by Arashvscode** [tyron12233/CodeAssist#320]
![Screenshot_۲۰۲۲۰۳۱۰-۱۷۱۱۱۵_CodeAssist](https://user-images.githubusercontent.com/101287880/157674259-40aa5203-dbb9-4121-9e37-d27f0e1c31fb.jpg)
#52

**Comment by Arashvscode** [comment]
Why did this happen? The text compiler works too late in both java and xml

**Comment by Zeyrox1090** [comment]
what??

**Comment by tyron12233** [comment]
This is the intended auto closing of XML Tags behavior. if you wish to close it right away the `/>`.

Example: 
```xml
<EditText
    android:attribute="value" />
```

**Comment by Arashvscode** [comment]
> This is the intended auto closing of XML Tags behavior. if you wish to close it right away the `/>`.
> 
> Example:
> 
> ```
> <EditText
>     android:attribute="value" />
> ```

Tnks

**Comment by Arashvscode** [comment]
issue close
