### ISSUE TITLE
Attention please!!!!

### ISSUE THREAD

**Issue by MuzamilAliBhutto** [tyron12233/CodeAssist#321]
In xml files there are no suggestions for library view ie: com.google.android.toolbar.please update it.Thanks.

**Comment by tyron12233** [comment]
Please use an appropriate title for the issue and make it easier to recognize. Resubmit an issue by filling up [this template](https://github.com/tyron12233/CodeAssist/issues/new?assignees=&labels=&template=bug_report.md&title=)
