### ISSUE TITLE
How can I implmat library here 

### ISSUE THREAD

**Issue by Mdsarowarhossain** [tyron12233/CodeAssist#323]
Hello I want to implement some library in my project so how can I do this when I write code in query gradle but this library did on implemented

**Comment by hassanmahfuj** [comment]
Use Library Manager instead.
![IMG_20220312_230810~2](https://user-images.githubusercontent.com/37881727/158027695-7f9d6dfe-23dd-4861-af59-ed11e14e3a76.jpg)

**Comment by Mdsarowarhossain** [comment]
![Screenshot_20220313-102922](https://user-images.githubusercontent.com/98280301/158045130-55fd471f-31c8-48f5-95da-a61362948a3d.jpg)
Can you explain me about This input Fields

**Comment by tyron12233** [comment]
CodeAssist uses the maven naming convention for libraries. Read more about it (here)[https://maven.apache.org/guides/mini/guide-naming-conventions.html]

Example: `com.google.android.material:material:1.4.0`

Group ID: `com.google.android.material`
Artifact ID: `material`
Version: `1.4.0`

**Comment by ilyassesalama** [comment]
> CodeAssist uses the maven naming convention for libraries. Read more about it (here)[https://maven.apache.org/guides/mini/guide-naming-conventions.html]
> 
> Example: `com.google.android.material:material:1.4.0`
> 
> Group ID: `com.google.android.material` Artifact ID: `material` Version: `1.4.0`

Why don't you give an option to write `com.google.android.material:material:1.4.0` as a whole not separated in 3 fields, that'd be annoying and maybe confusing for the user. IMO, either add a checkbox to whether write `com.google.android.material:material:1.4.0` as a whole or use 3 input fields, or replace the 3 fields with one.

**Comment by hassanmahfuj** [comment]
Yes, i think it's annoying. We have to copy-paste 3 times.

**Comment by susandahal** [comment]
> Yes, i think it's annoying. We have to copy-paste 3 times.

You can add the library in build.gradle and then use the following option to add them to Library manager
![Screenshot_2022-03-30-13-54-34-356_com tyron code](https://user-images.githubusercontent.com/37948853/160783532-d2e730ad-e206-4c53-86e6-b192fb95c3f8.jpg)
