### ISSUE TITLE
External .jar file

### ISSUE THREAD

**Issue by Otang45** [tyron12233/CodeAssist#361]
Can I add external jar file to my project?

**Comment by hassanmahfuj** [comment]
Add to app/libs folder your jar files.

**Comment by tyron12233** [comment]
As what @hassanmahfuj said, you can directly paste the jar file on the app/build directly and it will automatically be added after you refresh the module.

Additionally, you can also add AAR files there.

**Comment by Otang45** [comment]
Ok thank sir

**Comment by yousefabdel1727** [comment]
Ok ... ? i go to try 🤔
