### ISSUE TITLE
An error occurred about the build

### ISSUE THREAD

**Issue by anthony-china** [tyron12233/CodeAssist#380]
Failed to remove ERROR when building build:/storage/emuLated/0/AndroCode/0kgo/app/build/ \n Please ask the author to solve it. My mobile phone is Huawei Hongmeng system.

**Comment by dingyi222666** [comment]
Please provide more detailed error logs or screenshots

**Comment by 17606657524** [comment]
![Uploading Screenshot_20220330_212821_com.tyron.code.jpg…]()

**Comment by 17606657524** [comment]
![Uploading Screenshot_20220330_212831_com.tyron.code.jpg…]()

**Comment by 17606657524** [comment]
> 请提供更详细的错误日志或截图
