### ISSUE TITLE
Unrecognized file error

### ISSUE THREAD

**Issue by Pichkandi** [tyron12233/CodeAssist#382]
I got an error and in this error my app can not opening and also i got warning of Unrecognized file generated-rule.txt and R.txt
Please fix it

**Comment by tyron12233** [comment]
The unrecognized file is just a warning and is most likely not an error or not the correct log.

**Comment by Pichkandi** [comment]
Please fix the app crash problem..
It's too much crashing in my phone..

मंगल, 5 अप्रैल 2022, 5:45 pm को tyron12233 ***@***.***> ने
लिखा:

**Comment by tyron12233** [comment]
You need to provide more details such as logs and what you did. Every time the app crashes you are presented the crash log and given an option to copy it. You can then send them here to help identify the issue.

Fill out the issue template properly at https://github.com/tyron12233/CodeAssist/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by Pichkandi** [comment]
Thank you for your response.
Well when i cut any single word or more word in java or xml file than 10
out of 7 time app crash.

मंगल, 5 अप्रैल 2022, 6:30 pm को tyron12233 ***@***.***> ने
लिखा:

**Comment by tyron12233** [comment]
Already fixed in 0.2.9
