### ISSUE TITLE
Sometimes deleted file come back!

### ISSUE THREAD

**Issue by hassanmahfuj** [tyron12233/CodeAssist#385]
After creating a file, if you build the project then delete the file, it comes back again.

1. Create a Java File.
2. Build debug APK.
3. Close project.
4. Open project again.
5. Delete that file.
6. Close project.
7. Open project again.
8. Your deleted file comes back again!!

 - Device: Redmi Note 8 Pro
 - OS: Android 11

I open my forked CodeAssist project in Android Studio. Try to figure it out. Find out `FileUtils.forceDelete(currentFile);` called without exception.

Edit1: The file deleted right away. But when the project closes, it comes back again.

**Comment by TorstenH82** [comment]
I can confirm that issue. Had the same problem of a re-appearing file after I deleted it with an external file manager.
