### ISSUE TITLE
Package name error when using Kotlin

### ISSUE THREAD

**Issue by kannano** [tyron12233/CodeAssist#392]
**Note that Issues are for bugs only. Use the discussions tab for feature requests.**

**Describe the bug**
App package name is getting error when I used two name separator (".")

**Screenshots**
[]()![Screenshot_2022-04-04-06-35-32-589_com.tyron.code.jpg](https://user-images.githubusercontent.com/47701056/161458224-a2732ccb-ee73-468a-8eb4-33d800ff85d3.jpg)
![Screenshot_2022-04-04-06-35-25-634_com.tyron.code.jpg](https://user-images.githubusercontent.com/47701056/161458234-4dd4ab3c-25cd-46e6-8c09-6e4c81c46304.jpg)
**Smartphone (please complete the following information):**
 - Device: Redmi Note 11
 - OS: Android 11
 - Version: 0.2.9ALPHA

**Additional context**
PLEASE TAKE THIS ISSUE INTO AN ACCOUNT SOLVE AS SOON AS POSSIBLE

**Comment by tyron12233** [comment]
`in` is a keyword in Kotlin and cannot be used in package names. In order to use `in` you need to `escape` it.

```kotlin
package `in`.file.explorer
```

**Comment by kannano** [comment]
Thanks
