### ISSUE TITLE
Some files are not saved in the storage

### ISSUE THREAD

**Issue by rdm600** [tyron12233/CodeAssist#40]
I don't know exactly which ones. After editing the file styles.xml I'm starting to assemble the project, everything is fine, the changes have taken effect. As soon as I start reassembling, the changes go back, i.e. rollback.

**Comment by tyron12233** [comment]
This is fixed in https://github.com/tyron12233/CodeAssist/commit/438232f6651799bf7ee6109cf1e2184ccf89e73f
