### ISSUE TITLE
ViewBinding cant work in kotlin project

### ISSUE THREAD

**Issue by BanDroid** [tyron12233/CodeAssist#400]
The kotlin compiler didn't recognized the databinding package path.

![Screenshot_2022-04-08-22-53-01-411_com.tyron.code.jpg](https://user-images.githubusercontent.com/68449470/162478734-1caa89d9-c2cb-4d93-a72e-4acee5f5de6c.jpg)

![Screenshot_2022-04-08-22-53-09-985_com.tyron.code.jpg](https://user-images.githubusercontent.com/68449470/162478785-125b6bf5-888d-4719-9df4-6825031ef6b0.jpg)

![Screenshot_2022-04-08-22-53-36-775_com.tyron.code.jpg](https://user-images.githubusercontent.com/68449470/162478826-7686d992-3adc-4f29-9745-ed3da39bff74.jpg)

**Comment by SubzeroSAD99** [comment]
I need a help with this
