### ISSUE TITLE
[Crash issue] [sora-editor] IndexOutOfBoundsException issue

### ISSUE THREAD

**Issue by Hakalle** [tyron12233/CodeAssist#401]
Hello Tyron, it is possible to update to latest version of `sora-editor`? For more information I need you to see this issue:
https://github.com/Rosemoe/sora-editor/issues/169

**Comment by PranavPurwar** [comment]
It is possible, but tyron might have to do some refactoring because CodeAssist uses a modified version of sora-editor

**Comment by MikeAndrson** [comment]
> It is possible, but tyron might have to do some refactoring because CodeAssist uses a modified version of sora-editor

Not since [this commit](https://github.com/tyron12233/CodeAssist/commit/bedd9907763cce56ca9ea2af107a5ab651359a10#diff-b6bdeb11fdbc74c33446e12d9a3e93e6834a4a2a2db26bf0e688fd0bc5bd94e9R36), it doesn't. (As of writing this the current version is 0.10.9, [see](https://github.com/tyron12233/CodeAssist/blob/main/code-editor/build.gradle#L43))

**Comment by PranavPurwar** [comment]
Yes, not for that commit/bug fix, but in this issue he/she has asked if tyron can update the version of [sora-editor](https://github.com/Rosemoe/sora-editor) to 0.10.11

**Comment by Hakalle** [comment]
> Not since [this commit](https://github.com/tyron12233/CodeAssist/commit/bedd9907763cce56ca9ea2af107a5ab651359a10#diff-b6bdeb11fdbc74c33446e12d9a3e93e6834a4a2a2db26bf0e688fd0bc5bd94e9R36), it doesn't. (As of writing this the current version is 0.10.9, [see](https://github.com/tyron12233/CodeAssist/blob/main/code-editor/build.gradle#L43))

I'm using a up-to-date version in my CodeAssist fork. But according to Rosemoe, Tyron needs to make new changes to the code editor to fix issues like: `IndexOutOfBoundsException`
