### ISSUE TITLE
One project was replaced by another

### ISSUE THREAD

**Issue by rdm600** [tyron12233/CodeAssist#41]
As for me, this is a pretty critical bug.

There are two projects in CodeAssist. In appearance, when switching from one project to another, there are no difficulties, everything works smoothly.

The playback path of the problem was not found. But once again, when I wanted to switch from project #1 to project #2, project #1 disappeared, and only project #2 remained instead.

It turns out that one project was replaced by another.

**Comment by tyron12233** [comment]
I need more info about how to reproduce this issue

**Comment by tyron12233** [comment]
Does it still happen on the latest version?

**Comment by rfrizov** [comment]
> Does it still happen on the latest version?

Now I'll try to check

**Comment by rfrizov** [comment]
> Does it still happen on the latest version?

If I switch between projects quickly, so that one does not have time to be indexed, then there is a chance that I will get into the wrong project. I've been poking around until the project seems to have been deleted. But it's still a little scary, then it happened completely by accident :)

**Comment by tyron12233** [comment]
This may be from the old project system, in the current version the project system has been completely rewritten

**Comment by rdm600** [comment]
> This may be from the old project system, in the current version the project system has been completely rewritten

Thank you, I think the question can be closed.

**Comment by rdm600** [comment]
> This may be from the old project system, in the current version the project system has been completely rewritten

Horror! It happened again. Only under different circumstances.

1. I have an existing project
2. I entered this project
3. Then came out of it
4. Went to the project creation menu, selected a template.
5. Went back, clicked on an existing project
6. It is empty!!! (The Projects folder has disappeared in the application folder altogether)

To be honest, I don't understand why this happened

**Comment by rdm600** [comment]
@tyron12233 can you upload a new APK version with these fixes? I'm not going to just 🥺
