### ISSUE TITLE
Critical: compilation error with AndroidX libraries

### ISSUE THREAD

**Issue by rfrizov** [tyron12233/CodeAssist#43]
After the last update, the application stopped compiling the project, even a new one.
![Screenshot_20211211-211839_CodeAssist](https://user-images.githubusercontent.com/53654451/145687362-683e017f-97ec-4fb6-85cd-7587a7160edd.jpg)

**Comment by tyron12233** [comment]
Are you using the version from the releases?

**Comment by rfrizov** [comment]
> Вы пользуетесь версией из релизов?

Yes.

**Comment by tyron12233** [comment]
Ive added a new release which fixes this issue

https://github.com/tyron12233/CodeAssist/releases/tag/ALPHA-0.1.1
