### ISSUE TITLE
Questions about CodeAssist

### ISSUE THREAD

**Issue by rdm600** [tyron12233/CodeAssist#44]
I'm sorry that I combined everything into one question, but I think it will be more convenient this way.

Questions:
 — Will CodeAssist be published on Google Play?
— Will real error output be added when editing code? So that when you click on the error code, an Alert with error information is displayed. I also noticed that sometimes the text is not highlighted the first time and the Analyzing window appears ... (sometimes it interferes)
- Will cloning of projects from Git repositories be added?

Requests:
 — The same wish about allowing the project to be imported from a shared repository. Storing projects in the application folder is not very convenient, because the project directly depends on the existence of the application on the device + you will need to copy the existing project to the CodeAssist folder, well, at least inconvenient.

Thanks, that's it for me. I hope you pay attention

**Comment by tyron12233** [comment]
1. Yes, once the project reaches beta.
2. Currently if you long press on a code with an error, a toast will show with the current information about the error.
2.5. This is a limitation of the code editor library, there is no support for background highlighting yet so on large files, it waits till the analysis is complete and then highlight the file.
3. There are plans for adding git support, but its not a priority right now.
4. These are how android apps are supposed to work now (Creating directories on the root storage and leaving files upon uninstall is not recommended). On android 10 and above, android introduced FUSE which severely impacts performance of  operations with `java.io.File`. During compilation, a lot of reads and writes are performed by the compiler which will be slowed down running on a FUSE mounted storage. The only place where FUSE isn't mounted and the user can still access is the app's external storage directory

**Comment by tyron12233** [comment]
For more info about FUSE take a look at [this link](https://source.android.com/devices/storage/scoped)

One example of this affecting performance is with AIDE if you notice its nearly impossible to edit files smoothly on android 11

**Comment by rfrizov** [comment]
> 1. Yes, once the project reaches beta.
> 2. Currently if you long press on a code with an error, a toast will show with the current information about the error.
>    2.5. This is a limitation of the code editor library, there is no support for background highlighting yet so on large files, it waits till the analysis is complete and then highlight the file.
> 3. There are plans for adding git support, but its not a priority right now.
> 4. These are how android apps are supposed to work now (Creating directories on the root storage and leaving files upon uninstall is not recommended). On android 10 and above, android introduced FUSE which severely impacts performance of  operations with `java.io.File`. During compilation, a lot of reads and writes are performed by the compiler which will be slowed down running on a FUSE mounted storage. The only place where FUSE isn't mounted and the user can still access is the app's external storage directory

Thanks for the answers! Could you also please pay attention to this problem: https://github.com/tyron12233/CodeAssist/issues/41

I almost lost my project :(
