### ISSUE TITLE
Compilation in the background

### ISSUE THREAD

**Issue by rdm600** [tyron12233/CodeAssist#45]
When the application compiles the project in the background, the compilation freezes at the moment of Running IncrementalD8Task.

If you go into the application, it will "hang off" and continue compiling

Wish: you can make a pop-up notification with the <Install> button appear at the end of compilation, this will be more convenient. (Now the notification is coming in silent)

**Comment by PranavPurwar** [comment]
D8 is a memory extensive task, that's why it is blocked by android when in background
