### ISSUE TITLE
Where is my project saved?

### ISSUE THREAD

**Issue by pavel5750cz2** [tyron12233/CodeAssist#477]
Where is my project saved so i can backup? I dont see it in my phone even if i type my project in search bar in file explorer app for samsung.
Anyways i like your ide . I downloaeed this evening and i love it. Its like android studio but for android. I just wanna now know where is  the default store location?

**Comment by vladgba** [comment]
If android version is 11
  - default storage > "Android/data/com.tyron.code/files"

**Comment by pavel5750cz2** [comment]
> If android version is 11
> 
> * default storage > "Android/data/com.tyron.code/files"

![Screenshot_20220901-205252_My Files](https://user-images.githubusercontent.com/112654784/187990913-2c916d43-ede1-48b7-82b7-9e9393e6fe43.jpg)
Its not there

**Comment by pavel5750cz2** [comment]
> > If android version is 11
> > 
> > * default storage > "Android/data/com.tyron.code/files"
> 
> ![Screenshot_20220901-205252_My Files](https://user-images.githubusercontent.com/112654784/187990913-2c916d43-ede1-48b7-82b7-9e9393e6fe43.jpg) Its not there and i dont have folder called android in phone. Only on sd

Why now i cant even install the apk?
![Screenshot_20220901-205125_Package installer](https://user-images.githubusercontent.com/112654784/187991181-c4be49ea-80de-412a-9b55-34c1479a9d0c.jpg)
![Screenshot_20220901-205121_CodeAssist](https://user-images.githubusercontent.com/112654784/187991190-6b320eb0-b293-4673-9079-aad41736e78f.jpg)

**Comment by vladgba** [comment]
@pavel5750cz2 try internal storage instead of sdcard

**Comment by pavel5750cz2** [comment]
> @pavel5750cz2 try internal storage instead of sdcard

Ok now i gotta find how to move it there

**Comment by pavel5750cz2** [comment]
> > @pavel5750cz2 try internal storage instead of sdcard
> 
> Ok now i gotta find how to move it there

And also i will next time connect with my old github where i forgot password

**Comment by pavel5750cz2** [comment]
![Screenshot_20220901-213401_CodeAssist](https://user-images.githubusercontent.com/112654784/187997516-9e7e5a4b-57a5-4a95-a0a6-68821c327cf6.jpg)
Daam i cant retyoe to changw from sd

**Comment by vladgba** [comment]
Ok. Maybe standart file managers cant open data folders. Try to open with "Total Commander" this path:
"/storage/emulated/0/Android/data/com.tyron.code/files/Projects"
 - "/storage/emulated/0/" can be named as **phone memory** or **internal storage**

**Comment by pavel5750cz2** [comment]
> Ok. Maybe standart file managers cant open data folders. Try to open with "Total Commander" this path: "/storage/emulated/0/Android/data/com.tyron.code/files/Projects"
> 
> * "/storage/emulated/0/" can be named as **phone memory** or **internal storage**

It worked. I moved it to documents and when i opened it in file manager IT EVEN INSTALLED
