### ISSUE TITLE
Which key is the signature

### ISSUE THREAD

**Issue by rdm600** [tyron12233/CodeAssist#48]
If, for example, you build a project in Android Studio and sign it with a debug key, then "Play Protection: installation from an unknown developer" pops up during installation. And in CodeAssist, applications are signed so that Play protection does not appear. How do you do it? More precisely, what key? It just got interesting 😊

**Comment by Hax4us** [comment]
I am using key from my play console hence no unknown developer warning

**Comment by rdm600** [comment]
> I am using key from my play console hence no unknown developer warning

I was expecting a slightly wrong answer. I asked the developer what kind of signature scheme CodeAssist uses, and with what key it is all signed

**Comment by Hax4us** [comment]
> > I am using key from my play console hence no unknown developer warning
> 
> I was expecting a slightly wrong answer. I asked the developer what kind of signature scheme CodeAssist uses, and with what key it is all signed

i don't think that warning depends on signature scheme

**Comment by tyron12233** [comment]
Apps built by CodeAssist are currently signed with a debug certificate, that's why play protect doesn't warn users
