### ISSUE TITLE
Kotlin Completion not working

### ISSUE THREAD

**Issue by andihasan97** [tyron12233/CodeAssist#495]
**Note that Issues are for bugs only. Use the discussions tab for feature requests.**

**Describe the bug**
Kotlin Completion not working 

**To Reproduce**

**Expected behavior**
Repair 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [VivoY15 1901]
 - OS: [e.g. android 11 funtouch OS 9]
 - Version [11
![Screenshot_20220925_224630](https://user-images.githubusercontent.com/96150715/192175146-ef7cb3c3-8188-45fd-ab3e-081209fa280c.jpg)
]

**Additional context**

**Comment by AidosZhaqyp** [comment]
Should I tell you again that it isn't stable yet one more time? Look, no one officially said that Kotlin completion was enabled again, no commits about it and even CodeAssist's official repository in Github Actions doesn't have any test apk with that. You build that one on your own and complain about completion which was disable some versions ago. Do you see how funny situation is? And it won't work unless there are people like you who cries around every corner that it doesn't work.

**Comment by susandahal** [comment]
Tyron didn't actually say it works, and he hasn't even release any test builds regarding kotlin completions so it doesn't make sense you actually make this an issue

**Comment by andihasan97** [comment]
> Tyron didn't actually say it works, and he hasn't even release any test builds regarding kotlin completions so it doesn't make sense you actually make this an issue

I'm sorry, I am newbie user github
