### ISSUE TITLE
Cris

### ISSUE THREAD

**Issue by elcris1823** [tyron12233/CodeAssist#496]
**Note that Issues are for bugs only. Use the discussions tab for feature requests.**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sadiqdave** [comment]
Hey i can't create a project

**Comment by tyron12233** [comment]
Kindly edit this issue to best describe the issue you are facing by answering the bullet forms. If not, it will be considered stale and invalid.

**Comment by tyron12233** [comment]
Not enough info
