### ISSUE TITLE
Cache service respond 500

### ISSUE THREAD

**Issue by Deenu713** [tyron12233/CodeAssist#50]
![Screenshot_20211212-213632](https://user-images.githubusercontent.com/82932744/145719909-4fd3c47d-8850-471b-80c7-d0303075bf9b.png)

What's the error can you help me I tried every repo error same

**Comment by tyron12233** [comment]
Github cache service is down. For more information check [here](https://github.com/actions/cache/issues/698). Please do not open issues that are not related to the repo this is for CodeAssist bugs, for that ask a question on a discord server.
