### ISSUE TITLE
multiple libraries error 

### ISSUE THREAD

**Issue by a7m2005** [tyron12233/CodeAssist#529]
**Note that Issues are for bugs only. Use the discussions tab for feature requests.**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

hello, i added firebase libraries and when app building shows an error
**Duplicate Files from two libraries detected**

**Comment by DevVigilante** [comment]
Is Sketchware supports on iPhone devices?
