### ISSUE TITLE
Cursor stops at 21 Line of Code

### ISSUE THREAD

**Issue by hesa656** [tyron12233/CodeAssist#54]
Build version: 0.1.4 ALPHA
Build date: 1981-01-01 01:01:02
Current date: 2021-12-14 17:03
Device: Huawei Mate 20 Lite (Dual SIM)
Android Version: 10.0.0.286

Stack trace:
App doesn't crash (Bug)

The cursor in the editor stops at 21 Line of code - it cannot be moved to the lines below. 

The bug occurs when using the Microsoft SwiftKey keyboard, but does not occur when using another keyboard (e.g. Hacker Keyboard). A similar bug is in Sketchware Pro. 

Microsoft SwiftKey is a keyboard that I have been using for many years and I write on it the fastest. It would be nice if the Microsoft SwiftKey keyboard also works in CodeAssist. 

Bug video:

https://user-images.githubusercontent.com/48819648/146034881-75cc2d6f-1279-46d1-9c2d-73e53e4d0f6e.mp4

**Comment by tyron12233** [comment]
can you try disabling `Enable keyboard suggestions` in the settings as a workaround?

**Comment by hesa656** [comment]
Oh, it worked. 
Sorry I didn't check this before.
