### ISSUE TITLE
Gradle modules

### ISSUE THREAD

**Issue by TimScriptov** [tyron12233/CodeAssist#63]
CodeAssist support Gradle modules?

1.....
![Screenshot_20211217-202706.png](https://user-images.githubusercontent.com/31324315/146568085-46a82a9a-f3e1-44c1-8dc4-7fbddc25e61d.png)
---------------------------------
2.....
![Screenshot_20211217-202726.png](https://user-images.githubusercontent.com/31324315/146568239-2402b98d-98e3-4f0c-8028-b246c7a48d1c.png)
![Screenshot_20211217-202720.png](https://user-images.githubusercontent.com/31324315/146568257-d7d79131-600f-4313-889a-2bb7104d5d67.png)

**Comment by tyron12233** [comment]
No, CodeAssist only supports single module projects.
