### ISSUE TITLE
Is this a Bug or Android Restriction ??

### ISSUE THREAD

**Issue by Premjit-Chowdhury** [tyron12233/CodeAssist#64]
![Screenshot_2021-12-17-21-30-41-987_com tyron code](https://user-images.githubusercontent.com/72644801/146572986-e275214f-7210-4821-bfc0-d7ce63394914.jpg)
I have a question 
It is saying that i can save files in app's internal storage only and this is also editable but i can't change manually that default folder . If it can't be changed that default folder than make it non clickable for a11+ os .
@Iyxan23

**Comment by tyron12233** [comment]
The save location is not editable on android 11,  even if you were able to edit it it would display an error below (directory is not accessible)

**Comment by TimScriptov** [comment]
@tyron12233 https://developer.android.com/training/data-storage/manage-all-files

**Comment by tyron12233** [comment]
The problem is not about getting access to files, its about performance. Random read and writes with java.io.File is significantly slower on android 11 with FUSE mounted storage. Read the section `privacy over performance` [here](https://source.android.com/devices/storage/scoped)

**Comment by TimScriptov** [comment]
@tyron12233 Yes I know. File operations are very slow

**Comment by waelchateur** [comment]
so why not downgrade the sdk to 28 and use the old way to manage files as Aide did until u find out a better way

**Comment by tyron12233** [comment]
because its gonna be uploaded to play store
