### ISSUE TITLE
another maven proxy repos support

### ISSUE THREAD

**Issue by nobodyisherecu** [tyron12233/CodeAssist#72]
For some strange reason it doesn't get the existing repos form Gradle, will be a good idea and support the unsecure ones tho

**Comment by tyron12233** [comment]
Added on [this](https://github.com/tyron12233/CodeAssist/commit/b1f43ca39d26840db46b7b72ce0e27af0c8138d8) commit. For more information on how to add them take a look at [this](https://github.com/tyron12233/CodeAssist/issues/121#issuecomment-1026580828)
