### ISSUE TITLE
Problem with the backlight

### ISSUE THREAD

**Issue by rdm600** [tyron12233/CodeAssist#74]
After the last update, a white color began to appear instead of the backlight + if the color is white, then the hints also do not work. And sometimes it happens that when editing the code, the colors begin to "jump" along the letters in the strip.

**Comment by tyron12233** [comment]
are you editing the a kotlin class?

**Comment by rdm600** [comment]
> are you editing the a kotlin class?

Sorry, I forgot to send a screenshot. Java![1639843733573.jpg](https://user-images.githubusercontent.com/53654451/146648482-0c5f8b2c-ab4a-4caf-af86-e64b1f011857.jpg)

**Comment by tyron12233** [comment]
Do you have any steps to reproduce?

**Comment by rdm600** [comment]
> Do you have any steps to reproduce? 

There are no exact steps. But this happened after several compilations, after several switches between different files + there are about 15 JAVA classes in the project, half of which were open. Maybe because of this?

**Comment by tyron12233** [comment]
I think i have found it, ive forgot to set something. Let me test it out
