### ISSUE TITLE
FirebasePlease

### ISSUE THREAD

**Issue by bo0t** [tyron12233/CodeAssist#80]
I found it hard to add the firebase library please add it to the app

**Comment by thewolfprod** [comment]
Just choose what you need from Firebase and paste these lines into gradle.build
`
implementation 'com.google.firebase:firebase-auth:21.0.1'
`
`
implementation 'com.google.firebase:firebase-database:20.0.3'
`
`
implementation 'com.google.firebase:firebase-storage:20.0.0'
`
[Here are more libraries with their current versions](https://firebase.google.com/docs/android/setup?hl=en#available-libraries)

And find documentation on the Firebase website - I checked Firebase Auth and Database - they work. 

Alternatively, find examples of using Firebase on Github.

**Comment by bo0t** [comment]
Thanks bro
I wish u good luck
