### ISSUE TITLE
Kotlin

### ISSUE THREAD

**Issue by TimScriptov** [tyron12233/CodeAssist#82]
The old mistake is back
Compile kotlin failed:
![Screenshot_20211220-230249.png](https://user-images.githubusercontent.com/31324315/146812339-bcaf60d1-d382-4c19-bff6-626e37d523c7.png)

**Comment by tyron12233** [comment]
please make sure that you have the latest version, ConcurrentLongObjectHashMap is no longer 2799 lines long.

**Comment by tyron12233** [comment]
Does it still occur 0.1.9?

**Comment by tyron12233** [comment]
Im considering this as fixed, feel free to reopen this issue if you are still facing it
