### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by rdm600** [tyron12233/CodeAssist#86]
There are frequent leaks of RAM. For example, if there are many errors in the project code, if many compilations have been made. CodeAssist itself also starts to hang and sometimes an exception is thrown about a lack of memory. At the same time, about 1 GB of RAM is free on the phone at the moment.

**Comment by tyron12233** [comment]
fixed in https://github.com/tyron12233/CodeAssist/commit/e1d7d1661d2d943ec3bb44f1ddcc38e523dbb2e3
