### ISSUE TITLE
Do the best

### ISSUE THREAD

**Issue by Htet04** [tyron12233/CodeAssist#89]
![Screenshot_2021-12-23-15-12-59-39](https://user-images.githubusercontent.com/87855489/147213807-8375e54e-2e4c-46de-8936-ecccf445dcf7.png)
###**_And more thing but Get The Best_**

**Comment by tyron12233** [comment]
Thanks, its already fixed in [this](https://github.com/tyron12233/CodeAssist/commit/b93b5843108257872efda304a76b5912ae54d989) commit.
