### ISSUE TITLE
Delete the Project

### ISSUE THREAD

**Issue by MosesPitchai** [tyron12233/CodeAssist#97]
Hi!  Greetings!  I am excited when using this app.  Its really wonderful app for those want to create their app using smartphone.  

But there is no option to delete the project.  I could not delete the project.  And auto completion is not working for java language.

Thanking you.

**Comment by tyron12233** [comment]
The delete projects feature is already implemented in [this](https://github.com/tyron12233/CodeAssist/commit/4dbcb2344077e62de51be212d15923ff4ca8524c) commit.
