### ISSUE TITLE
Opening a random file

### ISSUE THREAD

**Issue by rdm600** [tyron12233/CodeAssist#98]
It happens that if a lot of files are open in the editor, then when you open a new file, it does not open, but opens a random file from already open ones.

**Comment by MikeAndrson** [comment]
Any specific steps to reproduce? Or a video of the issue?

**Comment by rdm600** [comment]
> Any specific steps to reproduce? Or a video of the issue?

The playback step is to have many files open. The most interesting thing is that this does not always happen, so I do not know how to reproduce it exactly.

**Comment by favourpro** [comment]
> It happens that if a lot of files are open in the editor, then when you open a new file, it does not open, but opens a random file from already open ones.

Whats the ram of your device
