### ISSUE TITLE
App does not save project on exit

### ISSUE THREAD

**Issue by Bandika71** [tyron12233/CodeAssist#99]
It is a good app but it needs to be fixed so the app can save the files on exit.

**Comment by tyron12233** [comment]
Hi, the current behavior is to save all the files when the editor is no longer visible. e.g. swiping back to the home screen, moving to another file, moving to another app. Can you tell me the way you exited the app?

**Comment by Bandika71** [comment]
Hi.I taped on home screen to go to Google Chrome because I wanted to copy
some text (recycler view dependency to build.gradle) ,but when I went back
to the app I could not find my project

tyron12233 ***@***.***> ezt írta (időpont: 2021. dec. 25.,
Szo 7:17):

**Comment by Bandika71** [comment]
Actually before I switched to Chrome I went back to main page of the app

Nepo Kramnik ***@***.***> ezt írta (időpont: 2021. dec. 25.,
Szo 7:21):

**Comment by Bandika71** [comment]
By the way this app would be very good for me because of
dependency.injection

Nepo Kramnik ***@***.***> ezt írta (időpont: 2021. dec. 25.,
Szo 7:29):

**Comment by tyron12233** [comment]
This has been fixed now, thanks!
